backend:
  name: github
  repo: postkomik/postkomik.github.io
  branch: main
publish_mode: editorial_workflow
media_folder: "assets/images/uploads"


collections:

 - label: "Tags"
   name: "tags"
   widget: "select"
   multiple: true
   options: ["Design", "UX", "Dev"]
   default: ["Design"]
    
  - name: "komik"
    label: "komik"
    folder: "komik"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
       - {label: "Layout", name: "layout", widget: "hidden", default: "komik"}
       - {label: "Title", name: "title", widget: "string"}
       - {label: "date", name: "date", widget: "datetime"}
       - {label: "type", name: "type", widget: "select", options: ["Manga", "Manhua", "Manhwa"]}
       - {label: "category", name: "category", widget: "{{slug}}"}
       - {label: "tag", name: "tag", widget: "inline-select", options: ["Action","Adventure","Fantasy","Martial Arts","Supernatural","Comedy"]}
       
  - name: radio_select
    label: Most recent framework
    widget: inline-select
    options:
      - { value: react, label: React }
      - { value: angular, label: Angular 1.x }
      - { value: vue, label: Vue.js }
      - { value: $, label: jQuery }  
      
  - name: "post" # Used in routes, e.g., /admin/collections/blog
    label: "Post" # Used in the UI
    folder: "_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Categories", name: "categories", widget: "string"}
      - {label: "Tags", name: "tags", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "BeforeToc", name: "beforetoc", widget: "string"}
      - {label: "Toc", name: "toc", widget: "true"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Rating (scale of 1-5)", name: "rating", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}    
      
  - name: "page" # Used in routes, e.g., /admin/collections/blog
    label: "Pages" # Used in the UI
    folder: "_pages" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Permalink", name: "permalink", widget: "string"}
      - {label: "Comments", name: "comments", widget: "true"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
      
  
  
  - name: "categori" # Used in routes, e.g., /admin/collections/blog
    label: "Categori" # Used in the UI
    folder: "_category" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "categori"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Permalink", name: "permalink", widget: "string"}
      - {label: "Comments", name: "comments", widget: "true"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
      
      

   
      
      
      
 
